/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoginForm: typeof import('./src/components/organisms/loginForm.vue')['default']
    Navbar: typeof import('./src/components/organisms/navbar.vue')['default']
    NavBar: typeof import('./src/components/organisms/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
